[package]
name = "controller"
version = "0.1.0"
authors = ["Maid Dog <maiddogsrl@gmail.com>"]

[dependencies]
log = "0.3"
env_logger = "0.4"
serial_enumerate = "0.1"

[dependencies.xbee]
path = "../.."
